config/routes.rb
Rails.application.routes.draw do

  namespace :core do
    get 'ui/render_tab/:tab_key' => 'ui#render_tab', as: :ui_render_tab
    get 'workflow/:source_type/:source_id/validate_transition/:target_state' => 'workflow#validate_transition', as: :workflow_validate_transition
    get 'workflow/:source_type/:source_id/perform_action/:initial_state/:target_state/:action_name' => 'workflow#perform_action', as: :workflow_perform_action
    post 'workflow/:source_type/:source_id/perform_action_frontend/:action_name' => 'workflow#perform_action_frontend', as: :workflow_perform_action_frontend
    get 'workflow/:source_type/:source_id/make_transition/:initial_state/:target_state' => 'workflow#make_transition', as: :workflow_make_transition
  end

  scope module: 'core' do
    resources :skills
    resources :roles
    resources :comments do
      member do
        get :cancel
      end
    end
    resources :invoices
    resources :quotes
    get 'project_logs' => 'activity_logs#project_log'
    get 'lead_logs' => 'activity_logs#lead_log'
    get 'invoice_logs' => 'activity_logs#invoice_log'
  end

  scope module: 'workspace' do
    resources :calendars do
      member do
        get :share
      end
    end
    resources :events do
      collection do
        get :show_task
      end
    end
    resources :audits
    resources :calendar_entries
    resources :user_assignments
    get 'switch_task_completed' => 'user_assignments#switch_task_completed'
    get 'completed_tasks' => 'user_assignments#completed_tasks'

  end

  get 'logout' => 'sessions#destroy', :as => 'logout'
  get 'login' => 'sessions#new', :as => 'login'
  get 'enumerations/sort' => 'enumerations#sort'
  get '/dashboard/tab_content' => 'dashboard#tab_content'
  post '/update_task' => 'pms/projects#update_task'

  resources :sessions
  resources :enumerations do
    get :sort, on: :collection
    collection do
    end
  end

  scope module: 'directory' do
    resources :contacts
    resources :resources
    resources :users
    resources :accounts
  end

  scope module: 'crm' do
    resources :leads
    get '/quick_note/:note_type_id/:notable_id/:notable_type' => 'leads#quick_note', as: :quick_note
    post '/create_quick_note' => 'leads#create_quick_note', as: :create_quick_note
  end

  scope module: 'core' do
    resources :notes do
      collection do
        get :search
        get :tab_content
      end
      member do
        get :cancel
      end
    end
  end

  scope module: 'pms' do
    resources :projects
    resources :tasks
    resources :task_lists do
      collection do
        get :edit_task
        get :delete_task
        post :create_task
        post :update_task
        get :switch_task_completion
      end
      member do
        get :cancel
        get :add_task
      end

    end
  end

  namespace :admin do
    get 'settings', action: 'edit', controller: 'settings', :as => :settings
    post 'settings', action: 'update', controller: 'settings'
    resources :note_types do
      member do
        get :make_default
      end
    end
    resources :custom_fields
    resources :organization_units
  end

  root :to => 'workspace/calendars#index'

  scope module: 'api' do
    scope module: 'crm' do
      post 'api/leads' => 'leads#create'
    end
  end

end

app/models/pms.rb
module Pms
  def self.table_name_prefix
    'pms_'
  end
end

app/models/pms/project.rb
# == Schema Information
#
# Table name: pms_projects
#
#  id               :integer          not null, primary key
#  title            :string(255)
#  description      :text
#  start_date       :date
#  end_date         :date
#  user_id          :integer
#  created_at       :datetime
#  updated_at       :datetime
#  account_id       :integer
#  manager_id       :integer
#  planned_end_date :date
#  cost             :float
#  status_id        :integer
#  percentage_done  :integer
#  lead_id          :integer
#

class Pms::Project < ActiveRecord::Base
  audited

  include Noteable

  validates :title, presence: true

  belongs_to :status, class_name: 'Core::Status'

  belongs_to :user, class_name: Directory::User
  has_many :projects_users, class_name: 'Pms::ProjectsUser', dependent: :destroy
  has_many :assigned_users, through: :projects_users, source: :user

  has_many :projects_contacts, class_name: 'Pms::ProjectsContact', dependent: :destroy
  has_many :assigned_contacts, through: :projects_contacts, source: :contact
  has_many :invoices, class_name: 'Core::Invoice'
  has_many :quotes, class_name: 'Core::Quote'

  belongs_to :account, class_name: 'Directory::Account'
  belongs_to :manager, class_name: 'Directory::User'
  belongs_to :lead, class_name: 'Crm::Lead'

  has_many :task_lists, as: :taskable
  has_many :attachments, as: :fileable, class_name: 'Attachment'

  accepts_nested_attributes_for :attachments, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :projects_users, :reject_if => :all_blank, :allow_destroy => true
  accepts_nested_attributes_for :projects_contacts, :reject_if => :all_blank, :allow_destroy => true

  has_one :calendar, :class_name => 'Workspace::Calendar', as: :reference, dependent: :destroy
  after_create :setup_calender, :import_lead_data
  after_update :update_calendar
  after_destroy :remove_calendar

  def setup_calender
    colors = %w(#d1b391 #f15f74 #a9b0b0 #a0cdb3 #e66967 #f28e5a #69a3d2 #efdd78)
    cal = self.build_calendar
    cal.name = "#{self.title} Project"
    cal.color = colors.sample
    cal.user = self.user
    cal.save
  end

  def import_lead_data
    if self.lead
      self.invoices << self.lead.invoices
      self.quotes << self.lead.quotes
    end
  end

  def update_calendar
    setup_calender unless self.calendar
    self.calendar.name = "#{self.title} Project"
    self.calendar.save
  end

  def remove_calendar
    calendar = Workspace::Calendar.where(reference: self).first
    calendar.destroy if calendar
  end

  def calendar_entry_title
    "#{title}"
  end

  # Search methods
  #----------------------------------------------------
  include ElasticsearchSearchable

  def as_indexed_json(options={})
    {
        id: id,
        title: title,
        description: description,
        sort_title: title,
        start_date: start_date.present? ? "#{start_date}" : ''
    }
  end

  def self.filter_options
    {
        sorting: [
            {key: :sort_title, label: 'Title'},
            {key: :start_date, label: 'Start Date'}
        ],
        filter_box: [
            {key: :title, label: 'Title'},
            {key: :description, label: 'Description'},
        ],
        filter_aggregates: [
        ]
    }
  end
  #-----------------------------------------------------

  # Mappings
  # ------------------------------------------------------
  settings do
    mapping dynamic: true do
      [:sort_title, :start_date].each do |attr|
        indexes attr, type: 'string', index: :not_analyzed
      end
    end
  end
  # --------------------------------------------------------
end

app/models/pms/projects_contact.rb
# == Schema Information
#
# Table name: pms_projects_contacts
#
#  id         :integer          not null, primary key
#  contact_id :integer
#  project_id :integer
#  created_at :datetime
#  updated_at :datetime
#

class Pms::ProjectsContact < ActiveRecord::Base
  audited

  belongs_to :contact, class_name: 'Directory::Contact'
  belongs_to :project, class_name: 'Pms::Project'

  validates_uniqueness_of :contact_id, scope: [:project_id]

end

app/models/pms/projects_user.rb
# == Schema Information
#
# Table name: pms_projects_users
#
#  id         :integer          not null, primary key
#  user_id    :integer
#  project_id :integer
#  created_at :datetime
#  updated_at :datetime
#

class Pms::ProjectsUser < ActiveRecord::Base
  audited

  belongs_to :user, class_name: 'Directory::User'
  belongs_to :project, class_name: 'Pms::Project'

  validates_uniqueness_of :user_id, scope: [:project_id]

end

app/models/pms/task.rb
# == Schema Information
#
# Table name: pms_tasks
#
#  id           :integer          not null, primary key
#  description  :text
#  task_list_id :integer
#  user_id      :integer
#  due_date     :date
#  completed    :boolean          default(FALSE)
#  created_at   :datetime
#  updated_at   :datetime
#

class Pms::Task < ActiveRecord::Base
  audited

  acts_as_commentable class_name: 'Core::Comment'

  belongs_to :user, class_name: 'Directory::User'
  belongs_to :task_list, class_name: 'Pms::TaskList'

  validates :description, :task_list_id, :user_id, :due_date, presence: true

  has_many :tasks_users, class_name: 'Pms::TasksUser'
  has_many :assigned_users, through: :tasks_users, source: :user
  has_many :attachments, as: :fileable, class_name: 'Attachment'

  accepts_nested_attributes_for :tasks_users, :reject_if => :all_blank, :allow_destroy => true
  accepts_nested_attributes_for :attachments, reject_if: :all_blank, allow_destroy: true

  has_one :calendar_entry, :class_name => 'Workspace::CalendarEntry', as: :reference, dependent: :destroy
  after_create :setup_calender_entries
  after_update :update_calender_entries

  def setup_calender_entries
    entry = self.build_calendar_entry
    entry.title = self.description.length > 255 ? self.description[0..50].html_safe : self.description
    entry.start_date = self.due_date
    entry.end_date = self.due_date
    entry.calendar = self.task_list.taskable.calendar
    entry.save
  end

  def update_calender_entries
    setup_calender_entries unless self.calendar_entry
    if self.changed? or self.calendar_entry.new_record?
      self.calendar_entry.title = self.description.length > 255 ? self.description[0..50].html_safe : self.description
      self.calendar_entry.start_date = self.due_date
      self.calendar_entry.end_date = self.due_date
      self.calendar_entry.calendar = self.task_list.taskable.calendar
      self.calendar_entry.save
    end
  end

  def project
    ((task_list and task_list.taskable_type == "Pms::Project") ? task_list.taskable : nil)
  end

  def user_name
    user ? [user.first_name, user.last_name, user.username] : []
  end
  # Search methods
  #----------------------------------------------------
  include ElasticsearchSearchable

  def as_indexed_json(options={})
    {
        description: description,
        user: user_name,
        project: (project ? project.title : nil),
        created_date: created_at.strftime("%Y-%m-%d")
    }
  end

  def self.filter_options
    {
        filter_box: [

        ],
        filter_aggregates: [

        ]
    }
  end
  #-----------------------------------------------------
end

app/models/pms/task_list.rb
# == Schema Information
#
# Table name: pms_task_lists
#
#  id            :integer          not null, primary key
#  title         :string(255)
#  taskable_id   :integer
#  taskable_type :string(255)
#  created_at    :datetime
#  updated_at    :datetime
#  billable      :boolean          default(FALSE)
#

class Pms::TaskList < ActiveRecord::Base
  audited

  validates :title, presence: true
  belongs_to :taskable, polymorphic: true
  has_many :tasks, dependent: :destroy
  has_one :invoice, class_name: 'Core::Invoice'

  def complete_tasks
   self.tasks.where('completed = ?', true)
  end

  def incomplete_tasks
    self.tasks.where('completed = ?', false)
  end

  def taskable_type=(sType)
    super(sType.to_s.classify.constantize.base_class.to_s)
  end

end

app/models/pms/tasks_user.rb
# == Schema Information
#
# Table name: pms_tasks_users
#
#  id         :integer          not null, primary key
#  user_id    :integer
#  task_id    :integer
#  created_at :datetime
#  updated_at :datetime
#

class Pms::TasksUser < ActiveRecord::Base
  audited

  belongs_to :user, class_name: 'Directory::User'
  belongs_to :task, class_name: 'Pms::Task'

  validates_uniqueness_of :user_id, scope: [:task_id]
end

app/controllers/pms/projects_controller.rb
class Pms::ProjectsController < ApplicationController

  def index
    @page_title = 'Projects'
    add_breadcrumb 'PMS', projects_path
    add_breadcrumb 'Projects', projects_path
    @search = ESSearch.new
    @search.klass = current_user.created_projects
    @search.init_params params
    @search.load_records = false
    @projects = @search.search.records
  end

  def new
    @page_title = 'Projects'
    add_breadcrumb 'PMS', projects_path
    add_breadcrumb 'Projects', projects_path
    add_breadcrumb 'New Project'
    @project = Pms::Project.new
    @project.projects_contacts.build unless @project.projects_contacts.present?
    @project.projects_users.build unless @project.projects_users.present?
  end

  def create
    @project = Pms::Project.new(project_params)
    @project.user = current_user
    if @project.save
      redirect_to project_path(@project)
    else
      @page_title = 'Projects'
      add_breadcrumb 'PMS', projects_path
      add_breadcrumb 'Projects', projects_path
      add_breadcrumb 'New Project'
      render :new
    end
  end

  def edit
    @project = Pms::Project.find(params[:id])
    @page_title = @project.try(:title)
    add_breadcrumb 'PMS', projects_path
    add_breadcrumb 'Projects', projects_path
    @project.projects_contacts.build unless @project.projects_contacts.present?
    @project.projects_users.build unless @project.projects_users.present?
  end

  def update
    @project = Pms::Project.find(params[:id])
    if @project.update_attributes(project_params)
      redirect_to project_path(@project)
    else
      @page_title = @project.try(:title)
      add_breadcrumb 'PMS', projects_path
      add_breadcrumb 'Projects', projects_path
      render :edit
    end
  end

  def show
    @project = Pms::Project.find(params[:id])
    @page_title = @project.title
    @metadata = @project.try(:status)
    @invoices = Core::Invoice.where("project_id = ? or lead_id = ?", @project.id, @project.try(:lead).try(:id))
    @quotes = Core::Quote.where("project_id = ? or lead_id = ?", @project.id, @project.try(:lead).try(:id))
  end

  def destroy
    @project = Pms::Project.find(params[:id])
    @project.destroy
    redirect_to projects_path
  end

  private

  def project_params
    params.require(:pms_project)
    .permit(
        :title, :description, :start_date, :end_date, :account_id, :manager_id, :lead_id, :status_id, :percentage_done, :planned_end_date, :cost,
        projects_users_attributes: [:id, :user_id, :_destroy],
        projects_contacts_attributes: [:id, :contact_id, :_destroy],
        attachments_attributes: [:id, :name, :_destroy]
    )
  end
end

app/controllers/pms/task_lists_controller.rb
class Pms::TaskListsController < ApplicationController
  before_action :set_task_lisk, only: [:edit, :update, :destroy, :cancel, :add_task, :show]

  def new
    @task_list = Pms::TaskList.new
    @project = Pms::Project.find(params[:project_id])
    @task_list.taskable = @project
  end

  def create
    @task_list = Pms::TaskList.new(task_list_params)
    @task_list.save
    @project = @task_list.taskable
  end

  def edit
  end

  def update
    @task_list.update_attributes(task_list_params)
    @project = @task_list.taskable
  end

  def destroy
    @project = @task_list.taskable
    @task_list.destroy
  end

  def cancel
    @project = @task_list.taskable
  end

  def show
  end

  def add_task
    @task = Pms::Task.new
    @task.task_list = @task_list
  end

  def create_task
    @task = Pms::Task.new(task_params)
    @task.user = current_user
    @task.save
    @task_list = @task.task_list
    get_tasks
  end

  def edit_task
    @task = Pms::Task.find(params[:task_id])
    @task_list = @task.task_list
  end

  def update_task
    @task = Pms::Task.find(params[:pms_task][:id])
    @task.update_attributes(task_params)
    @task_list = @task.task_list
    get_tasks
  end

  def delete_task
    @task = Pms::Task.find(params[:task_id])
    @task_list = @task.task_list
    @task.destroy
    get_tasks
  end

  def switch_task_completion
    @task = Pms::Task.find(params[:task_id])
    @task.update_attribute(:completed, !@task.completed)
    @task_list = @task.task_list
    get_tasks
  end

  private

  def get_tasks
    @complete_tasks = @task_list.complete_tasks.order('created_at desc')
    @incomplete_tasks = @task_list.incomplete_tasks.order('created_at desc')
  end

  def set_task_lisk
    @task_list = Pms::TaskList.find(params[:id])
  end

  def task_list_params
    params.require(:pms_task_list)
    .permit(
        :title, :description, :project_id, :taskable_id, :taskable_type
    )
  end

  def task_params
    params.require(:pms_task)
    .permit(
        :due_date, :task_list_id, :description, tasks_users_attributes: [:id, :user_id, :_destroy]
    )
  end
end

app/controllers/pms/tasks_controller.rb
class Pms::TasksController < ApplicationController
  def show
    @task = Pms::Task.find(params[:id])
    @page_title = @task.task_list.taskable.title
  end
end

app/helpers/pms/projects_helper.rb
module Pms::ProjectsHelper
end

app/helpers/pms/task_lists_helper.rb
module Pms::TaskListsHelper
end

app/views/pms/task_lists/_task.html.slim
- unless task.completed
  div class="content action-hover" id="task_edit_#{task.id}"
    a.author style="margin-left: -21px;"
      = check_box_tag 'completed', task.id, task.completed, class: 'task_complete'
      = "<b>#{task.description}</b>".html_safe
    .metadata
      span.date
        - task.assigned_users.each do |user|
          span class='tagged_user'
            = link_to "#{user.first_name}", user_path(user), class: 'item'
      span.date.hide-display
        = link_to('Edit', edit_task_task_lists_path(:task_id => task.id), remote: true, class: 'edit')
        = link_to(semantic_icon('trash medium icon'), delete_task_task_lists_path(:task_id => task.id),remote:true, data: {confirm: 'Are you sure!'}, class: 'edit')
    .text
      = "Due Date #{task.due_date}"


- else
    div class="content action-hover" id="task_edit_#{task.id}"
      a.author style="margin-left: -21px;"
      .metadata
        span.date
          = check_box_tag 'completed', task.id, task.completed, class: 'task_complete'
          = "#{task.description} Completed"
        span.date.hide-display
          = link_to(semantic_icon('trash medium icon'), delete_task_task_lists_path(:task_id => task.id),remote:true, data: {confirm: 'Are you sure!'}, class: 'edit')

app/views/pms/task_lists/add_task.js.erb
$("#add_task_list_task_<%=@task_list.id%>").html("<%= escape_javascript render(partial: 'pms/task_lists/task_form', locals: {task: @task, task_list: @task_list}) %>");

app/views/pms/task_lists/cancel.js.erb
$('#project_task_lists').html("<%= escape_javascript render(partial: 'pms/projects/task_list', collection: @project.task_lists.order('created_at desc')) %>");

app/views/pms/task_lists/create.js.erb
$('#project_task_lists').html("<%= escape_javascript render(partial: 'pms/projects/task_list', collection: @project.task_lists.order('created_at desc')) %>");
$('#add_task_list').html('');

app/views/pms/task_lists/create_task.js.erb
$("#task_list_complete_tasks_<%=@task_list.id%>").html("<%= escape_javascript render(partial: 'pms/task_lists/task', collection: @complete_tasks) %>");
$("#task_list_incomplete_tasks_<%=@task_list.id%>").html("<%= escape_javascript render(partial: 'pms/task_lists/task', collection: @incomplete_tasks) %>");
$("#add_task_list_task_<%= @task_list.id%>").html('');

app/views/pms/task_lists/delete_task.js.erb
$("#task_list_complete_tasks_<%=@task_list.id%>").html("<%= escape_javascript render(partial: 'pms/task_lists/task', collection: @complete_tasks) %>");
$("#task_list_incomplete_tasks_<%=@task_list.id%>").html("<%= escape_javascript render(partial: 'pms/task_lists/task', collection: @incomplete_tasks) %>");

app/views/pms/task_lists/destroy.js.erb
$('#project_task_lists').html("<%= escape_javascript render(partial: 'pms/projects/task_list', collection: @project.task_lists.order('created_at desc')) %>");

app/views/pms/task_lists/edit.html.slim
= render partial: 'form', locals: { task_list: @task_list}

app/views/pms/task_lists/edit_task.js.erb
$("#task_edit_<%=@task.id%>").html("<%= escape_javascript render(partial: 'pms/task_lists/task_form', locals: {task: @task, task_list: @task_list}) %>");

app/views/pms/task_lists/new.js.erb
$('#add_task_list').html("<%= escape_javascript render(partial: 'pms/task_lists/form', locals: {task_list: @task_list}) %>");

app/views/pms/task_lists/show.html.slim
- content_for :sub_action_bar
  /= link_to 'Edit', edit_task_list_path(@task_list), :class => 'ui blue button'
  = link_to 'Delete', task_list_path(@task_list), method: :delete,  data: {confirm: 'Are you sure you want to delete!'}, class: 'ui blue button'

.ui.form
  .ui.grid
    .three.column.row
      .column
        table.ui.basic.table
          tbody
            = show_for @task_list do |u|
              = u.attribute :title
              = u.attribute :description


/= render_tabs( [{:name => 'task_list', :partial => '/pms/projects/task_lists', :label => 'Task List'}], @project)

app/views/pms/task_lists/switch_task_completion.js.erb
$("#task_list_complete_tasks_<%=@task_list.id%>").html("<%= escape_javascript render(partial: 'pms/task_lists/task', collection: @complete_tasks) %>");
$("#task_list_incomplete_tasks_<%=@task_list.id%>").html("<%= escape_javascript render(partial: 'pms/task_lists/task', collection: @incomplete_tasks) %>");

app/views/pms/task_lists/update.js.erb
$('#project_task_lists').html("<%= escape_javascript render(partial: 'pms/projects/task_list', collection: @project.task_lists.order('created_at desc')) %>");

app/views/pms/task_lists/update_task.js.erb
$("#task_list_complete_tasks_<%=@task_list.id%>").html("<%= escape_javascript render(partial: 'pms/task_lists/task', collection: @complete_tasks) %>");
$("#task_list_incomplete_tasks_<%=@task_list.id%>").html("<%= escape_javascript render(partial: 'pms/task_lists/task', collection: @incomplete_tasks) %>");
//$('#add_todo_task_<%=@task_list.id%>').html('');