config/routes.rb
Rails.application.routes.draw do

  namespace :core do
    get 'ui/render_tab/:tab_key' => 'ui#render_tab', as: :ui_render_tab
    get 'workflow/:source_type/:source_id/validate_transition/:target_state' => 'workflow#validate_transition', as: :workflow_validate_transition
    get 'workflow/:source_type/:source_id/perform_action/:initial_state/:target_state/:action_name' => 'workflow#perform_action', as: :workflow_perform_action
    post 'workflow/:source_type/:source_id/perform_action_frontend/:action_name' => 'workflow#perform_action_frontend', as: :workflow_perform_action_frontend
    get 'workflow/:source_type/:source_id/make_transition/:initial_state/:target_state' => 'workflow#make_transition', as: :workflow_make_transition
  end

  scope module: 'core' do
    resources :skills
    resources :roles
    resources :comments do
      member do
        get :cancel
      end
    end
    resources :invoices
    resources :quotes
    get 'project_logs' => 'activity_logs#project_log'
    get 'lead_logs' => 'activity_logs#lead_log'
    get 'invoice_logs' => 'activity_logs#invoice_log'
  end

  scope module: 'workspace' do
    resources :calendars do
      member do
        get :share
      end
    end
    resources :events do
      collection do
        get :show_task
      end
    end
    resources :audits
    resources :calendar_entries
    resources :user_assignments
    get 'switch_task_completed' => 'user_assignments#switch_task_completed'
    get 'completed_tasks' => 'user_assignments#completed_tasks'

  end

  get 'logout' => 'sessions#destroy', :as => 'logout'
  get 'login' => 'sessions#new', :as => 'login'
  get 'enumerations/sort' => 'enumerations#sort'
  get '/dashboard/tab_content' => 'dashboard#tab_content'
  post '/update_task' => 'pms/projects#update_task'

  resources :sessions
  resources :enumerations do
    get :sort, on: :collection
    collection do
    end
  end

  scope module: 'directory' do
    resources :contacts
    resources :resources
    resources :users
    resources :accounts
  end

  scope module: 'crm' do
    resources :leads
    get '/quick_note/:note_type_id/:notable_id/:notable_type' => 'leads#quick_note', as: :quick_note
    post '/create_quick_note' => 'leads#create_quick_note', as: :create_quick_note
  end

  scope module: 'core' do
    resources :notes do
      collection do
        get :search
        get :tab_content
      end
      member do
        get :cancel
      end
    end
  end

  scope module: 'pms' do
    resources :projects
    resources :tasks
    resources :task_lists do
      collection do
        get :edit_task
        get :delete_task
        post :create_task
        post :update_task
        get :switch_task_completion
      end
      member do
        get :cancel
        get :add_task
      end

    end
  end

  namespace :admin do
    get 'settings', action: 'edit', controller: 'settings', :as => :settings
    post 'settings', action: 'update', controller: 'settings'
    resources :note_types do
      member do
        get :make_default
      end
    end
    resources :custom_fields
    resources :organization_units
  end

  root :to => 'workspace/calendars#index'

  scope module: 'api' do
    scope module: 'crm' do
      post 'api/leads' => 'leads#create'
    end
  end

end

app/models/core.rb
module Core
  def self.table_name_prefix
    'core_'
  end
end

app/models/core/address.rb
# == Schema Information
#
# Table name: core_addresses
#
#  id               :integer          not null, primary key
#  address1         :string(255)
#  address2         :string(255)
#  address_type     :string(255)
#  city             :string(255)
#  zip              :string(255)
#  state            :string(255)
#  country          :string(255)
#  addressable_id   :integer
#  addressable_type :string(255)
#  created_at       :datetime
#  updated_at       :datetime
#

class Core::Address < ActiveRecord::Base
  belongs_to :addressable, polymorphic: true
  audited only: [:address1, :address2, :city, :zip, :state, :country], on: [:create, :update, :destroy], associated_with: :addressable
  belongs_to :directory_account, :class_name => 'Directory::Account'

  def to_s
    "#{city}, #{zip}"
  end

end

app/models/core/comment.rb
# == Schema Information
#
# Table name: core_comments
#
#  id               :integer          not null, primary key
#  title            :string(50)       default("")
#  comment          :text
#  commentable_id   :integer
#  commentable_type :string(255)
#  user_id          :integer
#  role             :string(255)      default("comments")
#  created_at       :datetime
#  updated_at       :datetime
#
# Indexes
#
#  index_core_comments_on_commentable_id    (commentable_id)
#  index_core_comments_on_commentable_type  (commentable_type)
#  index_core_comments_on_user_id           (user_id)
#

class Core::Comment < ActiveRecord::Base

  include ActsAsCommentable::Comment

  belongs_to :commentable, :polymorphic => true

  default_scope -> { order('updated_at DESC') }

  # NOTE: install the acts_as_votable plugin if you
  # want user to vote on the quality of comments.
  #acts_as_voteable

  # NOTE: Comments belong to a user
  belongs_to :user, class_name: 'Directory::User'


  def project
  	((commentable_type == "Pms::Task" and commentable.task_list and commentable.task_list.taskable_type == "Pms::Project") ? commentable.task_list.taskable : nil)
  end
  # Search methods
  #----------------------------------------------------
  include ElasticsearchSearchable

  def as_indexed_json(options={})
    {
    	commentable_type: commentable_type,
        comment: comment,
        user: [user.first_name, user.last_name, user.username],
        project: (project ? project.title : nil),
        created_date: created_at.strftime("%Y-%m-%d")
    }
  end

  def self.filter_options
    {
        filter_box: [

        ],
        filter_aggregates: [

        ]
    }
  end
  #-----------------------------------------------------
end

app/models/core/custom_field.rb
# == Schema Information
#
# Table name: core_custom_fields
#
#  id              :integer          not null, primary key
#  type            :string(30)       default(""), not null
#  field_format    :string(30)       default(""), not null
#  regexp          :string(255)      default("")
#  min_length      :integer          default(0), not null
#  max_length      :integer          default(0), not null
#  required        :boolean          default(FALSE)
#  editable        :boolean          default(TRUE)
#  searchable      :boolean          default(FALSE)
#  scheduleable    :boolean          default(FALSE)
#  name            :string(255)      not null
#  default_value   :text
#  possible_values :text
#  position        :integer          default(0)
#  meta            :text
#  created_at      :datetime
#  updated_at      :datetime
#
# Indexes
#
#  index_core_custom_fields_on_type  (type)
#

class Core::CustomField < ActiveRecord::Base
  FIELD_FORMATS = %w(string text int float list date bool)
  serialize :possible_values
  has_many :values, :class_name => 'Core::CustomValue', dependent: :destroy
  validates_inclusion_of :field_format, :in => FIELD_FORMATS
  validates_presence_of :name, :field_format

  before_validation :configure_values

  def configure_values
    self.searchable = false if %w(int float date bool).include?(self.field_format)
    self.scheduleable = false unless self.field_format == 'date'
    true
  end

  validate :validate_presence_of_possible_values

  def validate_presence_of_possible_values
    if self.field_format == "list"
      errors.add(:possible_values, :blank) if self.possible_values.blank?
      errors.add(:possible_values, :invalid) unless self.possible_values.is_a? Array
    end
  end

  def form_input_format
    {string: 'string', text: 'wysi', int: 'integer', float: 'float', list: 'select', date: 'date_time_picker', bool: 'boolean'}[self.field_format.to_sym]
  end
end

app/models/core/custom_value.rb
# == Schema Information
#
# Table name: core_custom_values
#
#  id              :integer          not null, primary key
#  customized_id   :integer
#  customized_type :string(255)
#  custom_field_id :integer
#  value           :text
#  created_at      :datetime
#  updated_at      :datetime
#

class Core::CustomValue < ActiveRecord::Base
  belongs_to :custom_field, class_name: 'Core::CustomField'
  belongs_to :customized, polymorphic: true
  delegate :name, :field_format, :possible_values, :form_input_format, :editable?, :required?, :searchable?, :scheduleable?, to: :custom_field

  after_initialize :set_default_value
  after_save :make_calendar_entries
  after_destroy :remove_calendar_entries
  validate :validate_presence_of_required_value,
           :validate_format_of_value,
           :validate_type_of_value,
           :validate_length_of_value


  def set_default_value
    if new_record? && custom_field && (customized_type.blank? || (customized && customized.new_record?))
      self.value ||= custom_field.default_value
    end
  end

  def to_s
    value.to_s
  end

  private
  def validate_presence_of_required_value
    errors.add(:value, :blank) if required? && value.blank?
  end

  def validate_format_of_value
    if value.present?
      errors.add(:value, :invalid) unless custom_field.regexp.blank? or value =~ Regexp.new(custom_field.regexp)
    end
  end

  def validate_type_of_value
    if value.present?
      # Format specific validations
      case custom_field.field_format
        when 'int'
          errors.add(:value, :not_a_number) unless value =~ /\A[+-]?\d+\z/
        when 'float'
          begin
            ; Kernel.Float(value);
          rescue;
            errors.add(:value, :invalid)
          end
        when 'date'
          errors.add(:value, :not_a_date) unless value =~ /\A\d{4}-\d{2}-\d{2}\z/
        when 'list'
          errors.add(:value, :inclusion) unless custom_field.possible_values.include?(value)
      end
    end
  end

  def validate_length_of_value
    if value.present?
      errors.add(:value, :too_short, :count => custom_field.min_length) if custom_field.min_length > 0 and value.length < custom_field.min_length
      errors.add(:value, :too_long, :count => custom_field.max_length) if custom_field.max_length > 0 and value.length > custom_field.max_length
    end
  end

  def make_calendar_entries
    if scheduleable? and field_format == 'date'
      calendar_title = custom_field.meta.match(/\[calendar_title:(.*)\]/)[1]
      calendar = Workspace::Calendar.find_or_create_by(name: calendar_title, system_user_id: Core::EmbeddedUser.find_by_username('system_user').id)
      if calendar.new_record?
        calendar.color =  '#F15F74 '
      end
      entry = Workspace::CalendarEntry.new
      entry.title = "#{Core::NoteType.find(customized.note_type_id).try(:name)} : #{customized.notable.send(:calendar_entry_title)} "
      entry.description = customized.content
      entry.reference = customized.notable
      entry.calendar = calendar
      entry.start_date = Date.parse(value)
      entry.end_date = Date.parse(value)
      entry.save
    end
  end

  def remove_calendar_entries
    if scheduleable? and field_format == 'date'
      calendar_title = custom_field.meta.match(/\[calendar_title:(.*)\]/)[1]
      calendar = Workspace::Calendar.find_or_create_by(name: calendar_title, system_user_id: Core::EmbeddedUser.find_by_username('system_user').id)
      entry = Workspace::CalendarEntry.where(reference: customized.notable, calendar: calendar).first
      entry.destroy if entry
    end
  end
end

app/models/core/email.rb
# == Schema Information
#
# Table name: core_emails
#
#  id             :integer          not null, primary key
#  email          :string(255)
#  email_type     :string(255)
#  emailable_id   :integer
#  emailable_type :string(255)
#  created_at     :datetime
#  updated_at     :datetime
#

class Core::Email < ActiveRecord::Base
  #audited only: [:email, :email_type], on: [:create, :update, :destroy]
  belongs_to :emailable, polymorphic: true
  audited only: [:email, :email_type], on: [:create, :update, :destroy], associated_with: :emailable
end

app/models/core/email_type.rb
# == Schema Information
#
# Table name: core_enumerations
#
#  id         :integer          not null, primary key
#  name       :string(255)      not null
#  value      :string(255)
#  type       :string(255)
#  created_at :datetime
#  updated_at :datetime
#  position   :integer
#

class Core::EmailType < Core::Enumeration
  audited
end

app/models/core/embedded_user.rb
# == Schema Information
#
# Table name: core_system_users
#
#  id                           :integer          not null, primary key
#  first_name                   :string(255)      not null
#  last_name                    :string(255)      not null
#  username                     :string(255)
#  email                        :string(255)
#  crypted_password             :string(255)
#  salt                         :string(255)
#  remember_me_token            :string(255)
#  remember_me_token_expires_at :datetime
#  auth_mode                    :string(255)
#  time_zone                    :string(255)
#  type                         :string(255)
#  created_at                   :datetime
#  updated_at                   :datetime
#  last_login_at                :string(255)
#  phone                        :string(255)
#  theme                        :string(255)
#
# Indexes
#
#  index_core_system_users_on_email              (email)
#  index_core_system_users_on_remember_me_token  (remember_me_token)
#  index_core_system_users_on_type               (type)
#

class Core::EmbeddedUser <  Core::SystemUser
end

app/models/core/enumeration.rb
# == Schema Information
#
# Table name: core_enumerations
#
#  id         :integer          not null, primary key
#  name       :string(255)      not null
#  value      :string(255)
#  type       :string(255)
#  created_at :datetime
#  updated_at :datetime
#  position   :integer
#

class Core::Enumeration < ActiveRecord::Base
  audited
  validates :name, :value, presence: true, uniqueness: {:scope => :type}

  def to_s
    name
  end
end

app/models/core/invoice_split.rb
# == Schema Information
#
# Table name: core_enumerations
#
#  id         :integer          not null, primary key
#  name       :string(255)      not null
#  value      :string(255)
#  type       :string(255)
#  created_at :datetime
#  updated_at :datetime
#  position   :integer
#

class Core::InvoiceSplit < Core::Enumeration
  audited
end

app/models/core/invoice_split_type.rb
# == Schema Information
#
# Table name: core_enumerations
#
#  id         :integer          not null, primary key
#  name       :string(255)      not null
#  value      :string(255)
#  type       :string(255)
#  created_at :datetime
#  updated_at :datetime
#  position   :integer
#

class Core::InvoiceSplitType < Core::Enumeration
  audited
end

app/models/core/invoice_status.rb
# == Schema Information
#
# Table name: core_enumerations
#
#  id         :integer          not null, primary key
#  name       :string(255)      not null
#  value      :string(255)
#  type       :string(255)
#  created_at :datetime
#  updated_at :datetime
#  position   :integer
#

class Core::InvoiceStatus <  Core::Enumeration
  audited
  has_one :invoice, class_name: 'Core::Invoice'
end

app/models/core/job_title.rb
# == Schema Information
#
# Table name: core_enumerations
#
#  id         :integer          not null, primary key
#  name       :string(255)      not null
#  value      :string(255)
#  type       :string(255)
#  created_at :datetime
#  updated_at :datetime
#  position   :integer
#

class Core::JobTitle < Core::Enumeration
  audited
end

app/models/core/location.rb
# == Schema Information
#
# Table name: core_enumerations
#
#  id         :integer          not null, primary key
#  name       :string(255)      not null
#  value      :string(255)
#  type       :string(255)
#  created_at :datetime
#  updated_at :datetime
#  position   :integer
#

class Core::Location < Core::Enumeration
  audited
end

app/models/core/note_custom_field.rb
# == Schema Information
#
# Table name: core_custom_fields
#
#  id              :integer          not null, primary key
#  type            :string(30)       default(""), not null
#  field_format    :string(30)       default(""), not null
#  regexp          :string(255)      default("")
#  min_length      :integer          default(0), not null
#  max_length      :integer          default(0), not null
#  required        :boolean          default(FALSE)
#  editable        :boolean          default(TRUE)
#  searchable      :boolean          default(FALSE)
#  scheduleable    :boolean          default(FALSE)
#  name            :string(255)      not null
#  default_value   :text
#  possible_values :text
#  position        :integer          default(0)
#  meta            :text
#  created_at      :datetime
#  updated_at      :datetime
#
# Indexes
#
#  index_core_custom_fields_on_type  (type)
#

class Core::NoteCustomField < Core::CustomField
end

app/models/core/note_type_association.rb
# == Schema Information
#
# Table name: core_enumerations
#
#  id         :integer          not null, primary key
#  name       :string(255)      not null
#  value      :string(255)
#  type       :string(255)
#  created_at :datetime
#  updated_at :datetime
#  position   :integer
#

class Core::NoteTypeAssociation <  Core::Enumeration

  audited
  has_many :note_types_associations, class_name: 'Core::NoteTypesAssociations', dependent: :destroy, foreign_key:  :association_id
  has_many :assigned_note_types, through: :note_types_associations, source: :note_type
end

app/views/core/invoices/_form.html.slim
= simple_form_for @invoice, url:  @invoice.new_record? ? invoices_path : invoice_path, remote:true, :html => {class: "invoice-form"} do |f|
  .ui.grid
    .column
      = f.input :organization_unit_id, collection: Core::OrganizationUnit.sort_by_ancestry(Core::OrganizationUnit.all),  value_method: :id, label_method: :title_for_selects,  :include_blank => true, selected: @invoice.lead.present? ? @invoice.lead.try(:organization_unit_id) : @invoice.project.lead.try(:organization_unit_id)
      = f.input :invoice_project, as: :string, label: 'Project', input_html: {value: @invoice.project.nil? ? @invoice.invoice_project : @invoice.project.title}
      = f.input :invoice_task, label: 'Task'
      = f.input :task_list_id, label: 'Task List', collection: Pms::TaskList.where(billable: true, taskable_id: @invoice.project_id), value_method: :id, label_method: :title, selected: @invoice.try(:task_list_id), include_blank: true if @invoice.project.present?
      = f.input :cost
      = f.input :split_type_id, collection: Core::InvoiceSplitType.all, include_blank: false
      - if @invoice.status.nil?
        = f.input :status_id, collection: Core::InvoiceStatus.all, selected: Core::InvoiceStatus.find_by_name(Core::Invoice::DEFAULT_STATUS).nil? ? Core::InvoiceStatus.first.try(:id) : Core::InvoiceStatus.find_by_name(Core::Invoice::DEFAULT_STATUS).id
      -else
        = f.input :status_id, collection: Core::InvoiceStatus.all
      = f.input :due_date
      = f.input :lead_id, as: :hidden, value: @invoice.lead_id
      = f.input :project_id, as: :hidden, value: @invoice.project_id

      .actions
        = f.submit f.object.new_record? ? 'Add' : 'Update', class: "ui blue button"
        .ui.negative.button Cancel

app/views/core/invoices/_invoice.html.slim
tr data-invoice=invoice.id
  td
    i class="circle large icon" style="color:#{invoice.try(:status).try(:value)}"
  td.data-block
    strong
      = number_to_currency invoice.cost if invoice.cost
  td  = l invoice.due_date if invoice.due_date
  td  = invoice.try(:split_type)
  td  = invoice.project.present? ? invoice.project.title : invoice.invoice_project
  td  = invoice.task_list.try(:title)
  td.grey
    = link_to(semantic_icon('pencil').html_safe, edit_invoice_path(invoice), remote: true, class: 'grey')
    | |
    = link_to(semantic_icon('trash').html_safe, invoice_path(invoice), remote: true, data: {method: :delete, confirm: 'Are you sure?'}, class: 'grey')
    | |
    = link_to(semantic_icon('unhide').html_safe, invoice_path(invoice), class: 'grey')

app/views/core/invoices/_invoices.html.slim
.invoices-list-header
  .ui.buttons
    = link_to "#{semantic_icon('add')} Invoice".html_safe, new_invoice_path(project_id: project_id, lead_id: lead_id), class: "ui button", remote: true

  .ui.top_margin
    = render 'core/invoices/list'

app/views/core/invoices/_list.html.slim
table.ui.compact.table.data-listing
  thead
    tr
      th.one.wide.column Status
      th.two.wide.column Amount
      th.three.wide.column Due Date
      th.two.wide.column Split
      th.three.wide.column Project
      th Task List
      th Actions
  tbody.invoices-list
    = render partial: 'core/invoices/invoice', collection: @invoices.order('created_at DESC'), as: :invoice

app/views/core/invoices/_sidebar.html.slim
= filter_box_for @search
br
= filter_aggregates_for @search

app/views/core/invoices/create.js.erb
$('.invoices-list').prepend("<%= escape_javascript(render( partial: 'invoice', locals: {invoice: @invoice})) %>");
Heyday.UI.initJSElements();

app/views/core/invoices/destroy.js.erb
<% unless @invoice.errors.present? %>
    $('[data-invoice="<%= @invoice.id%>"]').remove();
<% end %>

app/views/core/invoices/edit.js.erb
Heyday.UI.showModal('Edit Invoice','<%= j render(partial: 'form') %>');
Heyday.UI.initJSElements();

app/views/core/invoices/index.html.slim
= content_for :sidebar
  = render 'sidebar', url: invoices_path

= content_for :action_bar
  .ui.dropdown.button.sort-menu
    i.sort.icon
    .menu
      = render 'shared/sorting'
  /= sort_link(@q, :first_name, 'Name', {}, class: 'item')
  /= sort_link(@q, :email, 'Email', {}, class: 'item')

  = listing_layout_switch

= content_for :sub_action_bar
  = render partial: 'shared/pagination', locals: {collection: @invoices}

- if params[:listing_layout] == 'table'

  table.ui.table.data-listing
    thead
      tr
        th Status
        th Service
        th Against
        th Lead/Client Name
        th Project
        th.text_right Amount
    tbody.invoices-list

      - @invoices.each do |invoice|

        tr.clickAble data-invoice=invoice.id href="#{invoice_path(invoice)}"
          td
            i class="circle large icon" style="color:#{invoice.try(:status).try(:value)}"

          td.grey = invoice.organization_unit.try(:title)
          - if (invoice.lead and invoice.project) or invoice.project
            td.grey = 'Project'
            td.grey = invoice.project.user.try(:name)
          - elsif invoice.lead
            td.grey = 'Lead'
            td.grey = invoice.lead.try(:name)
          -else
            td
            td
          td.grey = invoice.try(:project).try(:title)
          td.text_right.grey = number_to_currency invoice.cost

    tfoot
      tr
        td colspan=5
        td.text_right
          .text
            strong = "Total = #{number_to_currency @invoices.all.sum(:cost)}"

- elsif params[:listing_layout] == 'list'
  .ui.very.relaxed.divided.list.data-listing
    - @invoices.each do |invoice|
      .item.data-block
        .icon
          i class="circle large icon" style="color:#{invoice.try(:status).try(:value)}"
        .content
          .header
            .text
              strong = link_to "#{l invoice.due_date if invoice.due_date}", invoice_path(invoice)
              - unless invoice.organization_unit.nil?
                span.grey = " — #{invoice.organization_unit.title}"
          span.grey.info-block
            = label_with_icon invoice.cost.to_s, 'small dollar grey'
          span.grey.info-block
            = label_with_icon invoice.split_type, 'time grey'

app/views/core/invoices/new.js.erb
Heyday.UI.showModal('New Invoice','<%= j render(partial: 'form') %>');
Heyday.UI.initJSElements();

app/views/core/invoices/show.html.slim
#show-box
  .box_content
    .comment
      .content
        strong = "#{label_with_icon (l @invoice.due_date), 'empty calendar'}".html_safe
        .right.floated.padded
          = link_to 'Close', url_for(:back), class: 'ui black button small'
        .right.floated.padded
          = link_to 'Edit', edit_invoice_path(@invoice), class: 'ui blue button small', remote: true
        span.grey = " — #{@invoice.organization_unit.try(:title)}".html_safe
        .text.grey = number_to_currency @invoice.cost, precision: 2
        .text.grey = @invoice.split_type.try(:name)
        .text.grey = @invoice.task_list.try(:title)
        .text
          i class="circle large icon" style="color:#{@invoice.try(:status).try(:value)}"
      .description.grey
        = @invoice.invoice_project.html_safe
      .description.grey
        = @invoice.invoice_task.html_safe

  = render_tabs([{name: 'notes', partial: 'shared/notes', label: 'Notes', remote: false, locals: {object: @invoice}}])

app/views/core/invoices/update.js.erb
$('[data-invoice="<%= @invoice.id%>"]').remove();
$('.invoices-list').prepend("<%= escape_javascript(render( partial: 'invoice', locals: {invoice: @invoice})) %>");

$('#show-box').replaceWith("<%= escape_javascript(render( template: 'core/invoices/show', locals: {invoice: @invoice})) %>");

Heyday.UI.initJSElements();