config/routes.rb
Rails.application.routes.draw do

  namespace :core do
    get 'ui/render_tab/:tab_key' => 'ui#render_tab', as: :ui_render_tab
    get 'workflow/:source_type/:source_id/validate_transition/:target_state' => 'workflow#validate_transition', as: :workflow_validate_transition
    get 'workflow/:source_type/:source_id/perform_action/:initial_state/:target_state/:action_name' => 'workflow#perform_action', as: :workflow_perform_action
    post 'workflow/:source_type/:source_id/perform_action_frontend/:action_name' => 'workflow#perform_action_frontend', as: :workflow_perform_action_frontend
    get 'workflow/:source_type/:source_id/make_transition/:initial_state/:target_state' => 'workflow#make_transition', as: :workflow_make_transition
  end

  scope module: 'core' do
    resources :skills
    resources :roles
    resources :comments do
      member do
        get :cancel
      end
    end
    resources :invoices
    resources :quotes
    get 'project_logs' => 'activity_logs#project_log'
    get 'lead_logs' => 'activity_logs#lead_log'
    get 'invoice_logs' => 'activity_logs#invoice_log'
  end

  scope module: 'workspace' do
    resources :calendars do
      member do
        get :share
      end
    end
    resources :events do
      collection do
        get :show_task
      end
    end
    resources :audits
    resources :calendar_entries
    resources :user_assignments
    get 'switch_task_completed' => 'user_assignments#switch_task_completed'
    get 'completed_tasks' => 'user_assignments#completed_tasks'

  end

  get 'logout' => 'sessions#destroy', :as => 'logout'
  get 'login' => 'sessions#new', :as => 'login'
  get 'enumerations/sort' => 'enumerations#sort'
  get '/dashboard/tab_content' => 'dashboard#tab_content'
  post '/update_task' => 'pms/projects#update_task'

  resources :sessions
  resources :enumerations do
    get :sort, on: :collection
    collection do
    end
  end

  scope module: 'directory' do
    resources :contacts
    resources :resources
    resources :users
    resources :accounts
  end

  scope module: 'crm' do
    resources :leads
    get '/quick_note/:note_type_id/:notable_id/:notable_type' => 'leads#quick_note', as: :quick_note
    post '/create_quick_note' => 'leads#create_quick_note', as: :create_quick_note
  end

  scope module: 'core' do
    resources :notes do
      collection do
        get :search
        get :tab_content
      end
      member do
        get :cancel
      end
    end
  end

  scope module: 'pms' do
    resources :projects
    resources :tasks
    resources :task_lists do
      collection do
        get :edit_task
        get :delete_task
        post :create_task
        post :update_task
        get :switch_task_completion
      end
      member do
        get :cancel
        get :add_task
      end

    end
  end

  namespace :admin do
    get 'settings', action: 'edit', controller: 'settings', :as => :settings
    post 'settings', action: 'update', controller: 'settings'
    resources :note_types do
      member do
        get :make_default
      end
    end
    resources :custom_fields
    resources :organization_units
  end

  root :to => 'workspace/calendars#index'

  scope module: 'api' do
    scope module: 'crm' do
      post 'api/leads' => 'leads#create'
    end
  end

end

app/models/crm.rb
module Crm
  def self.table_name_prefix
    'crm_'
  end
end

app/models/crm/lead.rb
# == Schema Information
#
# Table name: crm_leads
#
#  id                   :integer          not null, primary key
#  email                :string(255)
#  skype                :string(255)
#  technology           :string(255)
#  source_id            :integer
#  description          :text
#  created_at           :datetime
#  updated_at           :datetime
#  state                :string(255)
#  user_id              :integer
#  phone                :string(255)
#  first_name           :string(255)
#  last_name            :string(255)
#  organization_unit_id :integer
#
# Indexes
#
#  index_crm_leads_on_state    (state)
#  index_crm_leads_on_user_id  (user_id)
#

class Crm::Lead < ActiveRecord::Base
  include Noteable
  audited
  validates_presence_of :first_name, :last_name, :email
  belongs_to :source, class_name: 'Core::Source'
  belongs_to :user, :class_name => 'Core::SystemUser'
  acts_as_taggable_on :technologies

  belongs_to :organization_unit, :class_name => 'Core::OrganizationUnit'

  has_many :leads_contacts, class_name: 'Crm::LeadsContact', dependent: :destroy
  has_many :assigned_contacts, through: :leads_contacts, source: :contact
  has_many :invoices, class_name: 'Core::Invoice', dependent: :destroy
  has_many :quotes, class_name: 'Core::Quote', dependent: :destroy
  has_one :project, class_name: 'Pms::Project'
  has_many :attachments, as: :fileable, class_name: 'Attachment'

  accepts_nested_attributes_for :attachments, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :taggings , reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :source , reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :leads_contacts, :reject_if => :all_blank, :allow_destroy => true

  # Calendar Entry Methods methods
  #----------------------------------------------------
  def calendar_entry_title
    "#{first_name} #{last_name}"
  end

  # Search methods
  #----------------------------------------------------
  include ElasticsearchSearchable

  def as_indexed_json(options={})
    {
        id: id,
        name: [first_name, last_name],
        email: email,
        description: description,
        technologies: technologies.pluck(:id) || [],
        source_id: source_id,
        status: self.send(self.class.state_column),
        organization_unit_id: self.organization_unit_id,
        sort_name: "#{first_name} #{last_name}",
        sort_email: email,
        created_date: created_at.strftime("%Y-%m-%d")
    }
  end

  def self.filter_options
    {
        sorting: [
            {key: :sort_name, label: 'Name'},
            {key: :sort_email, label: 'Email'}
        ],
        filter_box: [
            {key: :name, label: 'Name'},
            {key: :email, label: 'Email'}
        ],
        filter_aggregates: [
            {key: :status, label: 'Status', collection: Crm::Lead.new.workflow.states.inject({}) { |h, t| h[t] = t; h }},
            {key: :organization_unit_id, label: 'Service', collection: Core::OrganizationUnit.all.inject({}) { |h, t| h[t.id.to_s] = t.title; h }},
            {key: :technologies, label: 'Technology', collection: Crm::Lead.tag_counts_on(:technologies).inject({}) { |h, t| h[t.id.to_s] = t.name; h }},
            {key: :source_id, label: 'Source', collection: Core::Source.all.inject({}) { |h, t| h[t.id.to_s] = t.name; h }}

        ]
    }
  end

  #-----------------------------------------------------

  # Mappings
  # ------------------------------------------------------
  settings do
    mapping dynamic: true do
      [:sort_name, :sort_email].each do |attr|
        indexes attr, type: 'string', index: :not_analyzed
      end
    end
  end
  # ------------------------------------------------------

  # Workflow methods
  #----------------------------------------------------
  include Heyday::Workflow::DataEntity
  workflow workflow_class: 'LeadWorkflow', state_column: 'state'
  #----------------------------------------------------

  def create_new_taggings(lead_taggings)
    lead_taggings.each do |lead_tagging|
      if lead_tagging[1][:tag_id].to_i == 0
        tag = ActsAsTaggableOn::Tag.new name: lead_tagging[1][:tag_id]
        tag.save
        lead_tagging[1][:tag_id] = tag.id
      end
    end
  end

  def as_json(options= {})
    {id: self.id, text: self.name}
  end

  def name
    "#{first_name} #{last_name}"
  end
end

app/models/crm/leads_contact.rb
# == Schema Information
#
# Table name: crm_leads_contacts
#
#  id         :integer          not null, primary key
#  contact_id :integer
#  lead_id    :integer
#  created_at :datetime
#  updated_at :datetime
#

class Crm::LeadsContact < ActiveRecord::Base
  belongs_to :contact, class_name: 'Directory::Contact'
  belongs_to :lead, class_name: 'Crm::Lead'

  validates_uniqueness_of :contact_id, scope: [:lead_id]
end

app/controllers/api/crm/leads_controller.rb
class Api::Crm::LeadsController < Api::ApiController

  def create
    puts '#############################################'
    puts '#############################################'
    puts 'In Create Method'
    @lead = Crm::Lead.new(leads_params)
    @lead.source = params[:crm_lead][:source]
    @lead.user = Core::EmbeddedUser.find_by_username('system_user')
    @lead.organization_unit = params[:crm_lead][:org_unit]
    puts @lead.inspect
    puts '#############################################'
    puts '#############################################'
    @lead.save(validate: false)
    render nothing: true
  end

  def leads_params
    organization_unit = Core::OrganizationUnit.find_by(title: params[:crm_lead][:org_unit])
    source = Core::Source.find_by(name: params[:crm_lead][:source])
    params[:crm_lead][:org_unit] = organization_unit
    params[:crm_lead][:source] = source
    params.require(:crm_lead)
    .permit(:first_name, :last_name, :email, :phone, :description
    )
  end

  def split_name
    unless params[:name].nil?
      splitted_name = params[:name].split(' ')
      first_name = splitted_name.first
      splitted_name.shift
      last_name = splitted_name.join(' ')
      [first_name, last_name]
    end
  end
end

app/controllers/crm/leads_controller.rb
class Crm::LeadsController < ApplicationController
  menu_item :leads
  before_filter :load_lead, only: [:edit, :update, :show, :destroy]
  before_action :set_sort_params, only: [:index]

  def index
    add_breadcrumb 'CRM', leads_path
    add_breadcrumb 'Leads'
    @page_title = 'Leads'
    @search = ESSearch.new
    @search.klass = Crm::Lead
    @search.init_params params
    @search.load_records = false
    @leads = @search.search.records
  end

  def new
    @page_title = 'Leads'
    add_breadcrumb 'CRM', leads_path
    add_breadcrumb 'Leads', leads_path
    add_breadcrumb 'New Lead'
    @lead = Crm::Lead.new
    load_association
  end

  def create
    @lead = Crm::Lead.new
    @lead.assign_attributes(lead_attributes)
    @lead.user = current_user
    if @lead.save
      flash[:notice] = "Successfully created Lead."
      redirect_to lead_path(@lead)
    else
      @page_title = 'Leads'
      add_breadcrumb 'CRM', leads_path
      add_breadcrumb 'Leads', leads_path
      load_association
      render :action => 'new'
    end
  end

  def edit
    @page_title = "#{@lead.first_name} #{@lead.last_name}"
    add_breadcrumb 'CRM', leads_path
    add_breadcrumb 'Leads', leads_path
    load_association
  end

  def update
    if @lead.update_attributes(lead_attributes)
      flash[:notice] = "Successfully updated Lead."
      redirect_to lead_path(@lead)
    else
      @page_title = "#{@lead.first_name} #{@lead.last_name}"
      add_breadcrumb 'CRM', leads_path
      add_breadcrumb 'Leads', leads_path
      render :action => 'edit'
    end
  end

  def show
    @page_title = "#{@lead.first_name} #{@lead.last_name}"
    add_breadcrumb 'CRM', leads_path
    add_breadcrumb 'Leads', leads_path
    @metadata = @lead.send(@lead.state_column)
    @lead.build_source unless @lead.source.present?
    @lead.build_organization_unit unless @lead.organization_unit.present?
    @invoices = Core::Invoice.where("lead_id = ? or project_id = ?", @lead.id, @lead.try(:project).try(:id))
    @quotes = Core::Quote.where("lead_id = ? or project_id = ?", @lead.id, @lead.try(:project).try(:id))

  end

  def destroy
    @lead.destroy
    redirect_to leads_path
  end

  def quick_note
    puts params[:note_type_id].to_i.class
    @note = Core::Note.new(note_type_id: params[:note_type_id], notable_id: params[:notable_id].to_i, notable_type: params[:notable_type])
    @note.build_for_editing
  end

  def create_quick_note
    @note = Core::Note.new(quick_note_params)
    @note.user = current_user
    @note.save
  end

  def load_lead
    @lead = Crm::Lead.find(params[:id]) rescue nil
    redirect_to leads_path if @lead.blank?
  end

  def load_association
    @lead.taggings.build unless @lead.taggings.present?
    @lead.leads_contacts.build unless @lead.leads_contacts.present?
    #@lead.source.build unless @lead.source.present?
  end

  def self.default_view
    'categorized'
  end

  private

  def lead_attributes
    params.require(:crm_lead).permit(:first_name, :last_name, :email, :phone, :skype, :technology, :source, :description,:source_id,:technology_list, :state, :organization_unit_id,
    taggings_attributes: [:id, :tag_id, :taggable_id, :taggable_type, :tagger_id, :tagger_type, :rating, :context, :_destroy],
    leads_contacts_attributes: [:id, :contact_id, :_destroy],
    attachments_attributes: [:id, :name, :_destroy]
    )
  end

  def quick_note_params
    all_options = params.require(:core_note).fetch(:note_fields, nil).try(:permit!)
    params.require(:core_note)
    .permit(
        :id, :user_id, :notable_id, :notable_type, :content,
        :note_attachment, :note_type_id,
        attachments_attributes: [:id, :name, :_destroy],
        custom_values_attributes: [:id, :value, :custom_field_id, :customized_id, :customized_type]
    ).merge(:note_fields => all_options)
  end

  def set_sort_params
    params["q"] ||= {}
    params["q"]["sort_params"] ||= {}
    params["q"]["sort_params"]['id'] = 'desc'
  end

end

app/helpers/crm/leads_helper.rb
module Crm::LeadsHelper
  def lead_audits(lead)

    ######### Collection of all Audits related to current lead ########
    @audit = lead.audits

    ######### Sorting array of audits in descending order w.r.t to time attribute (created_at) ########
    @audit = @audit.sort_by{|e| e[:created_at]}.reverse

    return @audit
  end

end

app/views/crm/leads/_assign_contact.html.slim
.nested-fields
  .fields
    .inline.fields.optional.select.type-select
      = f.input :contact_id, label: false, input_html: { class:'select-create-field', data: { options: Directory::Contact.all , path: new_contact_path} }, include_blank: false, placeholder: 'Add Contact'
      .field
        = link_to_remove_association semantic_icon('trash icon') , f

app/views/crm/leads/_form.html.slim
- content_for :sub_action_bar
  = form_submit_button 'Save', '.lead-form'
  = link_to 'Cancel', url_for(:back), class: 'ui black button'
= simple_form_for @lead, url: {action: @lead.new_record? ? :create : :update}, :html => {:multipart => true,class: "lead-form"}   do |f|
  .ui.stackable.grid
    .ui.grid
      .column.padded.top
        = f.input :first_name, placeholder: 'First Name'
        = f.input :last_name, placeholder: 'Last Name'
        = f.input :email, placeholder: 'example@xyz.com'
        = f.input :phone, placeholder: 'Phone Number'
        = f.input :skype, placeholder: 'Skype'
        = f.input :description, as:  :wysi, placeholder: 'Description'
        = f.input :technology_list, input_html: {class: 'multiple-add-taggable-field', data: {options: Core::Skill.pluck(:name)}}, label: 'Technologies', placeholder: 'Technologies'
        = f.input :source_id, collection: Core::Source.all
        = f.input :organization_unit_id, :collection => Core::OrganizationUnit.sort_by_ancestry(Core::OrganizationUnit.all), value_method: :id, label_method: :title_for_selects, include_blank: true, label: 'Division/Vertical'
        .inline.field
          label Contacts
        .contacts
          = f.simple_fields_for :leads_contacts do |contact|
            = render 'crm/leads/assign_contact', :f => contact
          .links
            = link_to_add_association 'Add Contacts' , f, :leads_contacts, :partial => 'crm/leads/assign_contact'
        .inline.field
          label Attachments
        .attachments
          = f.simple_fields_for :attachments do |attachment|
            - if @lead.persisted?
              = render 'shared/show_attachments', :f => attachment
          .links
            = link_to_add_association 'Add Attachment', f, :attachments, :partial => 'shared/attachments_fields'

app/views/crm/leads/_quick_note_form.html.slim
= simple_form_for @note, url:  create_quick_note_path , :html => {:multipart => true, :remote => true} do |f|
  = f.input :content, label: 'Description', as: :wysi, placeholder: 'Enter Description'

  = f.simple_fields_for :custom_values do |cu|
    = cu.input :value, label: cu.object.name, as: cu.object.form_input_format, collection: cu.object.possible_values, required: cu.object.required?
    = cu.input :id, as: :hidden
    = cu.input :custom_field_id, as: :hidden
    = cu.input :customized_id, as: :hidden
    = cu.input :customized_type, as: :hidden

  #attachments
    = f.simple_fields_for :attachments do |attachment|
      - if @note.persisted?
        = render 'shared/show_attachments', :f => attachment
    .links
      = link_to_add_association 'Add Attachment', f, :attachments, :partial => 'shared/attachments_fields'

  = f.input :note_type_id, as: :hidden
  = f.input :notable_id, :as => :hidden
  = f.input :notable_type, :as => :hidden
  = f.input :id, :as => :hidden

  .actions
    = f.submit 'Add', class: "ui blue button"
    .ui.negative.button Cancel

app/views/crm/leads/_show_technologies.html.slim
.ui.form
  .ui.grid.gray
    .two.column.row
      .column
        .ui.small.black.header Technologies
        hr
        -@lead.taggings.each do |tagging|
          .field
            b.label = "#{tagging.try(:tag).try(:name)} : "
            = tagging.rating

app/views/crm/leads/_sidebar.html.slim
= filter_box_for @search
br
= filter_aggregates_for @search

app/views/crm/leads/_technologies.html.slim
h3 Technologies
= f.simple_fields_for :taggings do |t|  
  = render 'technologies/technologies_fields', :f => t
  .links
    = link_to_add_association 'Add Technlogies' , f, :taggings, :partial => 'technologies/technologies_fields'

= call_hook(:view_leads_technologies_form)

app/views/crm/leads/create_quick_note.js.erb
<% if @note.errors.present? %>
    setTimeout(function(){
        Heyday.UI.showModal('Quick Note', '<%= j render 'quick_note_form' %>', null , null ,'large');
    }, 550)
<% end %>

app/views/crm/leads/edit.html.slim
= render "form"

app/views/crm/leads/index.html.slim
= content_for :sidebar
  = render 'sidebar'

= content_for :action_bar
  = link_to semantic_icon('add'), new_lead_path, class: "ui button"

  .ui.dropdown.button.sort-menu
    i.sort.icon
    .menu
      = render 'shared/sorting'
      /= sort_link(@q, :name, 'Name', {}, class: 'item')
      /= sort_link(@q, :email, 'Email', {}, class: 'item')

  = listing_layout_switch do
    - link_to(semantic_icon('column layout'), '?listing_layout=categorized', class: "ui button #{(params[:listing_layout] == 'categorized' ? 'active' : '')}", data: {layout_type: 'categorized'})

= content_for :sub_action_bar
  = render partial: 'shared/pagination', locals: {collection: @leads}

- if params[:listing_layout] == 'table'
  table.ui.padded.table.data-listing
    thead
      tr
        th.four.wide Name
        th State
        th Vertical/Division
        th Email

    tbody
      - @leads.each do |lead|
        tr.data-block
          td
            .text
              strong = link_to "#{lead.first_name} #{lead.last_name}", lead_path(lead)
              .ui.pointing.dropdown
                i.dropdown.icon.data-actions
                .menu
                  = link_to 'Edit', edit_lead_path(lead), class: 'item'
                  = link_to 'Delete', lead_path(lead), data: {method: :delete, confirm: 'Are you sure you want to delete?'}, class: 'item'

          td.grey = lead.send(lead.state_column).try(:capitalize)
          td.grey = lead.organization_unit.nil? ? 'Not Specified' : lead.organization_unit.title
          td.grey = lead.email

- elsif params[:listing_layout] == 'list'
  .ui.very.relaxed.divided.list.data-listing
    - @leads.each do |lead|
      .item.data-block
        .icon
          span.grey.info-block = lead.send(lead.state_column).capitalize
        .content
          .header
            .text
              strong = link_to "#{lead.first_name} #{lead.last_name}", lead_path(lead)
              - unless lead.organization_unit.nil?
                span.grey = " — #{lead.organization_unit.title}"
              .ui.pointing.dropdown
                i.dropdown.icon.data-actions
                .menu
                  = link_to 'Edit', edit_lead_path(lead), class: 'item'
                  = link_to 'Delete', lead_path(lead), method: :delete, confirm: 'Are you sure you want to delete?', class: 'item'
          span.grey.info-block
            = label_with_icon lead.email, 'mail outline'

- elsif params[:listing_layout] == 'categorized'
  table.ui.celled.table.data-listing
    thead
      tr
        - LeadWorkflow.new.states.each do |state|
          th width="20%" = state.capitalize
    tbody
      tr
        - LeadWorkflow.new.states.each do |state|
          td.state-column data-state=state style="vertical-align:top;"
            - @leads.where(state: state).each do |lead|
              -  note_types = Core::NoteTypeAssociation.find_by_name(lead.class).try(:assigned_note_types)
              .ui.segment.data-block data-id="#{lead.id}"
                h4
                  strong = link_to "#{lead.first_name} #{lead.last_name}", lead_path(lead), class: 'item lead-heading'
                  - unless lead.organization_unit.nil?
                    span.grey.small-font = " — #{lead.organization_unit.title}"
                  .ui.pointing.dropdown
                    i.dropdown.icon.data-actions
                    .menu
                      - if note_types.present?
                        - note_types.each do |note_type|
                          = link_to note_type.name, quick_note_path(note_type_id: note_type.id, notable_id: lead.id, notable_type: lead.class), class: 'item', remote: true
                      = link_to 'Quote', new_quote_path(project_id: lead.project.try(:id), lead_id: lead.id), class: 'item', remote: true
                      = link_to 'Invoice', new_invoice_path(project_id: lead.project.try(:id), lead_id: lead.id), class: 'item', remote: true
                      = link_to 'Edit', edit_lead_path(lead), class: 'item'
                      = link_to 'Delete', lead_path(lead), method: :delete, data: {confirm: 'Are you sure you want to delete?'}, class: 'item'
                .skype.grey = lead.skype
                .email.grey = lead.email

app/views/crm/leads/new.html.slim
= render "form"

app/views/crm/leads/quick_note.js.erb
Heyday.UI.showModal('Quick Note', '<%= j render 'quick_note_form' %>', null , null ,'large');
Heyday.UI.initJSElements();

app/views/crm/leads/show.html.slim
- content_for :sub_action_bar
  = link_to 'Edit', edit_lead_path, :class => 'ui blue button'
  = link_to 'Delete', lead_path(@lead), method: :delete, data: {confirm: 'Are you sure you want to delete?'}, class: 'ui red button'
  = link_to 'Close', url_for(:back), class: 'ui black button'

- content_for :sidebar
  .ui.basic.accordion
    .title
      h3
        i.dropdown.icon
        |Contacts
    .content
      - @lead.assigned_contacts.each do |contact|
        .ui.vertical.segment
          strong = link_to "#{contact.name}", contact_path(contact)
          .text = "#{contact.email}"

.ui.grid.show
  .row
    .padded.top.column
      span
        = label_with_icon @lead.email, 'mail outline grey'
      span
        = label_with_icon @lead.phone, 'mobile outline grey'
      span
        = label_with_icon @lead.skype, 'skype outline grey'
      span
        = label_with_icon @lead.organization_unit.title, 'filter outline grey'
      span
        = label_with_icon @lead.source.name, 'bell outline grey'
  .row
    .column
      - unless @lead.technology_list.blank?
        span
          i.icon.terminal.grey
          = @lead.technology_list.join(', ')
  .row
    .column
      a.grey#show style="cursor:pointer"
      .ui.top_margin#description
        - unless @lead.attachments.blank?
          - @lead.attachments.each do |attachment|
            .file.ui.top_margin
              i.attachment.icon.grey
              = link_to "#{attachment.name.file.identifier} ".html_safe, attachment.name.url, target: '_blank'

        - unless @lead.description.blank?
          .ui.top_margin = @lead.try(:description).html_safe

= render_tabs([{name: 'notes', partial: 'shared/notes', label: 'Notes', remote: false, locals: {object: @lead}}, {name: 'quotes', partial: 'core/quotes/quotes', label: 'Quotes', remote: false, locals: {lead_id: @lead.id, project_id: @lead.try(:project).try(:id)}}, {name: 'invoices', partial: 'core/invoices/invoices', label: 'Invoices', remote: false, locals: {lead_id: @lead.id, project_id: @lead.try(:project).try(:id)}}])