config/routes.rb
Rails.application.routes.draw do

  namespace :core do
    get 'ui/render_tab/:tab_key' => 'ui#render_tab', as: :ui_render_tab
    get 'workflow/:source_type/:source_id/validate_transition/:target_state' => 'workflow#validate_transition', as: :workflow_validate_transition
    get 'workflow/:source_type/:source_id/perform_action/:initial_state/:target_state/:action_name' => 'workflow#perform_action', as: :workflow_perform_action
    post 'workflow/:source_type/:source_id/perform_action_frontend/:action_name' => 'workflow#perform_action_frontend', as: :workflow_perform_action_frontend
    get 'workflow/:source_type/:source_id/make_transition/:initial_state/:target_state' => 'workflow#make_transition', as: :workflow_make_transition
  end

  scope module: 'core' do
    resources :skills
    resources :roles
    resources :comments do
      member do
        get :cancel
      end
    end
    resources :invoices
    resources :quotes
    get 'project_logs' => 'activity_logs#project_log'
    get 'lead_logs' => 'activity_logs#lead_log'
    get 'invoice_logs' => 'activity_logs#invoice_log'
  end

  scope module: 'workspace' do
    resources :calendars do
      member do
        get :share
      end
    end
    resources :events do
      collection do
        get :show_task
      end
    end
    resources :audits
    resources :calendar_entries
    resources :user_assignments
    get 'switch_task_completed' => 'user_assignments#switch_task_completed'
    get 'completed_tasks' => 'user_assignments#completed_tasks'

  end

  get 'logout' => 'sessions#destroy', :as => 'logout'
  get 'login' => 'sessions#new', :as => 'login'
  get 'enumerations/sort' => 'enumerations#sort'
  get '/dashboard/tab_content' => 'dashboard#tab_content'
  post '/update_task' => 'pms/projects#update_task'

  resources :sessions
  resources :enumerations do
    get :sort, on: :collection
    collection do
    end
  end

  scope module: 'directory' do
    resources :contacts
    resources :resources
    resources :users
    resources :accounts
  end

  scope module: 'crm' do
    resources :leads
    get '/quick_note/:note_type_id/:notable_id/:notable_type' => 'leads#quick_note', as: :quick_note
    post '/create_quick_note' => 'leads#create_quick_note', as: :create_quick_note
  end

  scope module: 'core' do
    resources :notes do
      collection do
        get :search
        get :tab_content
      end
      member do
        get :cancel
      end
    end
  end

  scope module: 'pms' do
    resources :projects
    resources :tasks
    resources :task_lists do
      collection do
        get :edit_task
        get :delete_task
        post :create_task
        post :update_task
        get :switch_task_completion
      end
      member do
        get :cancel
        get :add_task
      end

    end
  end

  namespace :admin do
    get 'settings', action: 'edit', controller: 'settings', :as => :settings
    post 'settings', action: 'update', controller: 'settings'
    resources :note_types do
      member do
        get :make_default
      end
    end
    resources :custom_fields
    resources :organization_units
  end

  root :to => 'workspace/calendars#index'

  scope module: 'api' do
    scope module: 'crm' do
      post 'api/leads' => 'leads#create'
    end
  end

end

app/controllers/admin/note_types_controller.rb
class Admin::NoteTypesController < Admin::BaseController
  menu_item :note_types

  def index
    @page_title = 'Note Types'
    add_breadcrumb 'Admin', 'admin/settings'
    add_breadcrumb 'Note Types'
    redirect_to admin_note_type_path(Core::NoteType.first) if Core::NoteType.count > 0
  end

  def new
    @note_type = Core::NoteType.new
    @note_type.note_types_associations.build
  end

  def create
    @note_type = Core::NoteType.new
    @note_type.assign_attributes note_type_params
    if @note_type.save
      @success = true
    else
      @success = false
    end
  end

  def edit
    @note_type = Core::NoteType.find(params[:id])
  end

  def update
    @note_type = Core::NoteType.find(params[:id])
    if @note_type.update_attributes note_type_params
      @success = true
    else
      @success = false
    end
  end

  def show
    @note_type = Core::NoteType.find(params[:id])
    @page_title = @note_type.name
    add_breadcrumb 'Admin', 'admin/settings'
    add_breadcrumb 'Note Types'
    @custom_fields = @note_type.custom_fields
  end

  def make_default
    @note_type = Core::NoteType.find(params[:id])
    Core::NoteType.update_all(default: false)
    @note_type.update_attribute :default, true
  end

  private
  def note_type_params
    params.require(:core_note_type)
    .permit( :name, :default,
             note_types_associations_attributes: [:id, :association_id, :default, :commentable, :_destroy]
    )
  end
end

app/helpers/admin/note_types_helper.rb
module Admin::NoteTypesHelper
end

app/views/admin/note_types/_assign_association.html.slim
.nested-fields
  .fields
    .inline.field.optional.select.type-select
      = f.input :association_id, label: 'Linked With', collection: Core::NoteTypeAssociation.all, include_blank: false
      .ui.top_margin
        = f.input :default
        = f.input :commentable
      = link_to_remove_association semantic_icon('trash medium icon') , f

javascript:
  Heyday.UI.initJSElements();

app/views/admin/note_types/_form.html.slim
= simple_form_for @note_type, url: (@note_type.new_record? ? admin_note_types_path : admin_note_type_path(@note_type)), remote: true do |f|
  = f.input :name
  = f.simple_fields_for :note_types_associations do |association|
    = render 'admin/note_types/assign_association', f: association
  .links
    = link_to_add_association 'Add Association' , f, :note_types_associations , :partial => 'admin/note_types/assign_association'

  .actions
    = f.submit class: 'ui blue button'
    .ui.small.black.button.cancel Cancel

app/views/admin/note_types/_sidebar.html.slim
= content_for :sidebar
  = link_to 'New Note Type', new_admin_note_type_path, class: 'ui blue fluid button', remote: true

  .ui.vertical.secondary.pointing.menu
    - Core::NoteType.all.each do |note_type|
      = active_link_to note_type.name, admin_note_type_path(note_type), 'item'

app/views/admin/note_types/create.js.erb
<% if @success %>
Heyday.reload();
<% else %>
Heyday.UI.showModal('New Note Type', '<%= j(render 'form') %>');
<% end %>

app/views/admin/note_types/edit.js.erb
Heyday.UI.showModal('Edit Note Type', '<%= j(render 'form') %>');
Heyday.UI.initJSElements();

app/views/admin/note_types/index.html.slim
= render 'sidebar'

p Please create a new note type

app/views/admin/note_types/make_default.js.erb
Heyday.reload();

app/views/admin/note_types/new.js.erb
Heyday.UI.showModal('New Note Type', '<%= j(render 'form') %>');
Heyday.UI.initJSElements();

app/views/admin/note_types/show.html.slim
= render 'sidebar'

- content_for :sub_action_bar
  .buttons
    /= link_to 'Make Default', make_default_admin_note_type_path(@note_type), :class => 'ui button', remote: true unless @note_type.default?
    = link_to 'Edit', edit_admin_note_type_path(@note_type), :class => 'ui button', remote: true
    = link_to 'Add Custom Field', new_admin_custom_field_path(field_source: 'Note', field_meta: "[note_type:#{@note_type.id}]"), :class => 'ui blue button', remote: true
    = link_to 'Cancel', url_for(:back), class: 'ui black button'

h3.left.padded Custom Fields

table.ui.padded.table.data-listing
  thead
    tr
      th style="width: 30%" Name
      th Type
      th Required
      th Searchable
      th Scheduleable
  tbody
    - @custom_fields.each do |field|
      tr.data-block
        td
          strong = field.name
          .ui.pointing.dropdown
            i.dropdown.icon.data-actions
            .menu
              = link_to 'Edit', edit_admin_custom_field_path(field), class: 'item', remote: true
              = link_to 'Delete', admin_custom_field_path(field), method: :delete, data: {confirm: 'Are you sure you want to delete?'}, class: 'item', remote: true
        td.grey = field.field_format
        td.grey = field.required?
        td.grey = field.searchable?
        td.grey = field.scheduleable?

app/views/admin/note_types/update.js.erb
<% if @success %>
Heyday.reload();
<% else %>
Heyday.UI.showModal('Edit Note Type', '<%= j(render 'form') %>');
<% end %>